### ISSUE TITLE
Name changes?

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#1]
# Org name

I think `impy-cr` is not ideal for the org. Typical is something like `impy-project`, see https://github.com/root-project or https://github.com/crdb-project.

# Package name

I just noticed that the name `impy` is already taken on PyPI, which is very bad since people expect to be able to install something with `pip install <module-name>`.  :-(

https://pypi.org/project/impy

There is no good solution for this, all options have downsides.

1) Rename `impy` to X and grab the name on PyPI before someone else does.

Grabbing the name is easy, a source package upload will do. In Python it is expected nowadays that the package name on PyPI is the same as the module name. So if `impy` is renamed on PyPI, the python module should be renamed as well. If we rename to `foobar`, the following should work:
```
# in the shell
pip install foobar
# in Python
import foobar
```
This is the only option that is nice and consistent. I am aware that name changes at this point are already painful, since some people were already exposed to the name "impy", and it is a good name, it rolls off the tongue rather well! It would be a pity to change it.

You could name the module `impy_cr` and the package on PyPI `impy-cr`, this is another common model, see for instance `scikit-learn` (package) and `scikit_learn` (module), `boost-histogram` and `boost-histogram`. Then you could keep the org name as impy-cr then, so the github url would by impy-cr/impy-cr

The only thing I don't like about the name `impy-cr` is that impy is not really bound to cosmic rays. You can do with the simulated events whatever you like and it also includes Pythia, a non-CR model.

2) Keep the name `impy` for the module and instruct users to download it with a different package name, for example `impy-cr`. This option is not as consistent, but it is the change with the minimum of work and confusion.

```
# in the shell
pip install impy-cr
# in Python
import impy
```

The least amount of work, the org name can stay. We need to grab the name impy-cr on PyPI, but that can be done quickly.
It is not ideal if the package name is not identical to the module name, because people tend to expect this. In this case, it is a particularly problematic because a naive `pip install impy` works but it does not install what you expect!

**Comment by afedynitch** [comment]
Good point.

Renaming the project would make sense since the `pip install impy` dream just evaporated. The `_cr` was something that I spontaneously came up with when creating the org, maybe inspired by CRMC.

**Comment by afedynitch** [comment]
Suggestions:

- [ ] hapy (owned by scammer)
- [ ] haim (free)
- [ ] mchi (free)
- [ ] mcim (free)

**Comment by HDembinski** [comment]
Out of these options, I still like impy best, but I am doubly biased (I suggested it and I am now used to it).

Hippy? (not serious)

Hadronic Interaction models for Particle production in PYthon

**Comment by afedynitch** [comment]
I renamed the org to impy-project, since I want to post a link around in various ICRC proceedings. The repo will likely keep the name impy, PyPI can become impy-gen, or impy-mc and the package impy_gen/mc. Up to discussion.

**Comment by HDembinski** [comment]
I think this can be closed :)

**Comment by jncots** [comment]
Hi @HDembinski, I am currently testing uploading impy to Test PyPI. As it is discussed here `impy` name is taken. So, for a time being, I uploaded the package with name `impy-mc`. Do you have any suggestions to name it differently, when it will come to the stage of uploading to PyPI?

**Comment by HDembinski** [comment]
Thanks for reopening, when I closed it, I didn't realize that it is still an unsolved issue.

We should really try to pick a new name that works without a hyphen. A hyphen adds a lot of irriation, because people are so used to `pip install X; python -c "import X"` working, in other words that PyPI name and package name are the same. This can only be achieved with underscores.

Like with variable/method/function names, if you can invent a name without an underscore, great. It is much easier to type.

Anatoli suggested "hapy", but then we need to get the package first. It is a pretty clear-cut case, but this may take some time.

@jncots Do you have ideas for a name without a hyphen?

**Comment by HDembinski** [comment]
I asked ChatGPT to invent a few names. I list here the ones which ones I liked and which are not taken on PyPI.

partonix
hadronite
hadronova

Some short names that are not taken:

hadro
collidr
imgen
imcr
stronger
chromo

**Comment by HDembinski** [comment]
I like chromo. It rolls of the tongue and is easy to remember.

**Comment by jncots** [comment]
Another variant phigi (PHIGI, pHIGI, phiGI) (Particle Hadronic Interaction Generator Interface). Sounds like Fiji, so it would be easy to remeber and pronounce.

**Comment by afedynitch** [comment]
😂 I read it as piggy on my first attempt

**Comment by jncots** [comment]
I like Chromo, except it reminds Chrome.

**Comment by afedynitch** [comment]
Chromo resonates well with the fact that the models do some sort of QCD to simulate particle production

**Comment by afedynitch** [comment]
I filed a [PEP541 issue on pypi](https://github.com/pypa/pypi-support/issues/2495) to liberate the name `hapy`. I kind of like it. If it takes too long or there are issues with that, then I’m more into `chromo` rather than `phigi`.

**Comment by HDembinski** [comment]
I prefer chromo over hapy, because it sounds like harpy to me.

**Comment by afedynitch** [comment]
What’s wrong with harpy? :)

**Comment by afedynitch** [comment]
We discussed this once more among us, and I and @jncots like “chromo”, too. It’s a good name. We should go for it.

**Comment by HDembinski** [comment]
Right. Fortunately, github makes changing project urls relatively painless. Old URLs should be automatically forwarded to the new place.

I haven't checked whether the name `chromo` or `chromo-project` is available on Github. Is it?

I like it when the org is called like the main product, so chromo/chromo.

**Comment by HDembinski** [comment]
I have been thinking. Can't we just keep `impy-project` as the org name? The org does not have to have the same name as the project. Nobody really cares about the org name. It would be confusing if chromo would have a different name on github, but we can just rename the impy repo to chromo, and be done with it.

**Comment by HDembinski** [comment]
It looks like we can really close this now.
