### ISSUE TITLE
make parents index zero-based

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#100]
The parents array in EventData points to the parents of a particle. Currently, we use the original Fortran index (first particle is index 1, etc), but in Python, it is more natural to use zero-based indices, so that once can use parents to directly index the other arrays.

**Comment by afedynitch** [comment]
OK, but how would it work? Can we change default indexing in numpy? I didn't anything on the web that would allow to change the default.

One way would be to decrement parents and daughters by one. Since this is the only place where that would matter for the EventData.
