### ISSUE TITLE
PhoJet cannot handle projectiles other than protons

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#105]
The name "PhoJet" suggests that PhoJet can handle gamma + hadron collisions. However, when these are attempted, "PhoJet" crashes, see e.g. https://github.com/impy-project/impy/actions/runs/3724300209/jobs/6316372052#step:10:4256

PhoJet also crashes when hadrons (e.g. pi-) are used as projectiles.

**Comment by afedynitch** [comment]
Yes, true, PHOJet does gamma-gamma, gamma-hadron, as well as DPMJET, actually. But there are some specific settings (different proton PDF) required to run gammas. I could introduce some special case and add these settings but it needs to happen at initialization time and then the generator can not switch back to different primaries consistently. This has some historical non-scientific reasons dating back to my PhD.

We can leave this as a bug for while until I have more on-screen time. The two options to fix it are:
- Check if changing the PDF matters at all, so I would update the parameters file and hope that there is no need to re-fit cross sections
- If this has issues, implement workaround in impy to set the required settings and make sure that the beam particle config is not changes.

**Comment by HDembinski** [comment]
I think it is fine to restrict PhoJet to hadron-hadron for the time being, and leave out photon-hadron.

But hadron-hadron also do not work, is that expected?

Ralph always says that people should not use PhoJet anymore. How important is it that we have bindings for PhoJet? It sounds like DPMJet offers a superset of the functionality of PhoJet. In that case, PhoJet would only be interesting for historical reasons.

Or is it more complicated?

**Comment by afedynitch** [comment]
Phojet has some advantages compared to DPMJET. DPMJET uses a subset of information from PHOJET and simply wraps around it for events, where nuclei are not involved. But when doing this it loses quite some about event topology (MPI, diffractive cuts, etc). I still recommend using PHOJET for pp or h-p physics at high energies.

Nonetheless, I fixed the projectiles accepted by phojet, so it doesn't crash anymore in #90. So, we can close this or leave it until I find time to take care of the photon projectile fixes.

**Comment by afedynitch** [comment]
This issue can be closed since the description is not accurate anymore and the initial problem is gone. Photons in PHOJET and DPMJET need deeper fixing in the models and it's not a matter of chromo.
