### ISSUE TITLE
Enable h-A cross-section for sibyll

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#109]
It should be ok to use. The docs says:

    output:      
    SIGprod    particle production cross section (mb) (SIGprod = SIGT-SIGQE)
    SIGbdif    q.ela and ela beam diff. cross section
    SIGela     elastic cross section

_Originally posted by @afedynitch in https://github.com/impy-project/impy/pull/90#discussion_r1057517545_

**Comment by afedynitch** [comment]
@jncots Shouldn't this work by now?

**Comment by jncots** [comment]
> @jncots Shouldn't this work by now?

Yes, it works now. Solved in #169
