### ISSUE TITLE
Compatibility issues with numpy > 1.20

### ISSUE THREAD

**Issue by afedynitch** [impy-project/chromo#11]
For some reason, with numpy 1.21.2 only a part of symbols are exposed in python by the Floyd wrapped libraries.
To reproduce, compile with numpy 1.21.2 and check if `dir(sib23d)` contains the functions `sibini` or `isib_pdg2pid`.

For a temporal workaround downgrade numpy. With numpy 1.19.x this problem doesn’t occur.

**Comment by HDembinski** [comment]
I found the related bug in numpy https://github.com/numpy/numpy/issues/22648

**Comment by HDembinski** [comment]
I found a workaround. You can copy the folder f2py from numpy-1.19.5 into the corresponding folder of your local numpy installation. chromo will compile then.

**Comment by jncots** [comment]
Solved in #127
