### ISSUE TITLE
Chromo + RIVET

### ISSUE THREAD

**Issue by afedynitch** [impy-project/chromo#118]
I've been wondering if we could make `chromo` talking to RIVET. To achieve this, we need pyhepmc to write ASCII to stdout. RIVET uses pipes ([see here](https://gitlab.com/hepcedar/rivet/-/blob/release-3-1-x/doc/tutorials/firstrun.md)).

Is this possible with pyhepmc?

**Comment by afedynitch** [comment]
@jncots This is also fixed, no?

**Comment by jncots** [comment]
> @jncots This is also fixed, no?

Yes, RIVET reads files produced by pyhempc in chromo. Solved in #170
