### ISSUE TITLE
Add TALYS generator

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#134]
At the https://indico.uni-wuppertal.de/event/230/, Walter Winter and others requested that we add the TALYS generator

https://tendl.web.psi.ch/tendl_2019/talys.html

For the steering, I was told that we could get inspiration from CRPROPA.

**Comment by afedynitch** [comment]
I have some TALYS input files and output analysis from past work. But it is not a kinetic event generator, it is a Hauser-Feshbach code that calculates branching ratios into different nuclear channels using density functional theory. It doesn't compute the kinematics of the final state, AFAIU.

**Comment by HDembinski** [comment]
Ok, then it is out of scope, closing...
