### ISSUE TITLE
Installing chromo: NumPy version>1.21

### ISSUE THREAD

**Issue by gaudu** [impy-project/chromo#155]
After installing chromo using `python3 -m pip install --pre --upgrade chromo`, I encountered an error message asking me to use the version of NumPy 1.21 or less in order to call Numba: 

```
gaudu@gaudu-top:~$ chromo -h
Traceback (most recent call last):
  File "/home/gaudu/.local/bin/chromo", line 5, in <module>
    from chromo.cli import main
  File "/home/gaudu/.local/lib/python3.10/site-packages/chromo/__init__.py", line 1, in <module>
    from chromo import models
  File "/home/gaudu/.local/lib/python3.10/site-packages/chromo/models/__init__.py", line 1, in <module>
    from chromo.models.sophia import Sophia20
  File "/home/gaudu/.local/lib/python3.10/site-packages/chromo/models/sophia.py", line 2, in <module>
    from chromo.common import MCRun, MCEvent, CrossSectionData
  File "/home/gaudu/.local/lib/python3.10/site-packages/chromo/common.py", line 12, in <module>
    from chromo.util import (
  File "/home/gaudu/.local/lib/python3.10/site-packages/chromo/util.py", line 557, in <module>
    import numba as nb
  File "/usr/lib/python3/dist-packages/numba/__init__.py", line 205, in <module>
    _ensure_critical_deps()
  File "/usr/lib/python3/dist-packages/numba/__init__.py", line 145, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.21 or less")
ImportError: Numba needs NumPy 1.21 or less
```
In order to go around this, Hans pointed out a solution: create a python environment where one installs chromo again along with the NumPy version 1.21. I can now run chromo in this python environment.

Maybe chromo should be shipped with the NumPy version 1.21 or else?

**Comment by afedynitch** [comment]
Hi Chloé,
it seems like the numba version you had installed was not updated for longer time but numpy has been updated. 
`> import numba as nb` triggers the error and it is in principle unrelated to chromo. Could you try updating numba in your previous environment and check if the problem still persists? 

We actually don't require numba for the code to run since it's used for an optional acceleration of one of the routines. So you could also remove numba.

**Comment by HDembinski** [comment]
I think it is a good idea to remove the numba code. I am personally a big fan of numba, but it adds further complexity to this project, which is already complex. It is more work, but we can replace any numba accelerated code with a compiled extension using C++ and pybind11 to get similar speed ups.

**Comment by HDembinski** [comment]
Chloe we installed chromo in a virtual environment on your machine. This means you can install a different numba version inside that environment for chromo without affecting the rest of your installation.

@afedynitch I have to take a closer look, but I think that the rules in our dependencies are misconfigured. The current numba version cannot handle the current numpy version, so for numba to work we have to restrict the numpy version to <=1.23.

**Comment by afedynitch** [comment]
@jncots, have a look at [this](https://numba.readthedocs.io/en/stable/user/installing.html#version-support-information), the numba version is trailing numpy by 0.01. With the next numba release they will likely move to <1.2X or <2. (if 1.26 is the last 1.2x version). Then everything will get back in shape.

Right now there is at least one combination of binaries available with numpy 1.25 and numba 0.58.

**Comment by jncots** [comment]
Since chromo on PyPI works with numpy >= 1.23, numba >= 0.56.2 should be Ok. The issue could be closed.

**Comment by afedynitch** [comment]
Then we close it.
