### ISSUE TITLE
DPMJET stable/unstable settings

### ISSUE THREAD

**Issue by jncots** [impy-project/chromo#156]
There are couple of problems with setting particles for decay in DpmjetIII:

* If 
```python
for pdg in unstable_pids:
    dpmjet_generator.set_unstable(pdg)
```
is excecuted before any event generation, then the function `self._lib.dt_kkinc` in `_generate()` reset stable/unstable settings. It can be checked by inspecting the content of `self._lib.pydat3.mdcy[:, 0]` before and after the first call. In some cases stable/unstable settings are reset after the first call as well. It seems that reset occurs after each call for a new nucleus.

* Some particles (Sigma~+(-3112), Sigma-(3112), Sigma~-(-3222), Sigma+(3222), Xi~+(-3312), Xi-(3312), Xi~ 0(-3322), Xi0(3322), Omega~+(-3334), Omega-(3334), and some other) are still present as final particles, although `self._lib.pydat3.mdcy[:, 0]` shows that they are set as unstable. Partly, the problem is solved by setting `event_generator._lib.pydat1.mstj[22 - 1] = 1`, which sets decay for all particles that are set as unstable. For some reason, Dpmjet constructor sets `event_generator._lib.pydat1.mstj[22 - 1] = 2`. In that case only particles with proper time decay smaller than 10 mm decays. Setting long enought time by `event_generator._lib.pydat1.parj[71 - 1] = 1e10` should set all unstable particles for decay. However, in both cases Sigma-(3112),  Sigma0(3212), Sigma+(3222) still present in output. It can be solved, only if all particles are set as unstable by `self._lib.pydat3.mdcy[:, 0] = 1`, which in most cases don't want to do, as some particles should still be present in output (for example muons).  The problem seems appear only for nuclei. For proton as a target, Sigma particles disappear.

The first step to change the behaviour is to set `event_generator._lib.pydat1.mstj[22 - 1] = 1`, unless `event_generator._lib.pydat1.mstj[22 - 1] = 2` has special meaning. In that case we can add an interface function for `event_generator._lib.pydat1.parj[71 - 1]`.

The problem with not decaying Sigma particles is somewhere in Dpmjet and related somehow to nuclei.

For a record, I tried to set as unstable the particles with following pdg ids: 

```python
unstable_pids = [441, -3112, 3112, -3212, 3212, -3222,  3222, -3312, 3312, -3322, 3322, -3334, 3334, -4112, 4112, -4122, 4122, -4212, 4212, -4222, 4222]
```

**Comment by afedynitch** [comment]
Thanks, @jncots ! I have an idea what resets it. Could you perform the same test with PHOJET if you have a debug script? It shouldn’t happen there..

**Comment by jncots** [comment]
As I remember PHOJET doesn't have a problem with reseting, because it doesn't work with nuclei.
