### ISSUE TITLE
running example from readme

### ISSUE THREAD

**Issue by michael-pitt** [impy-project/chromo#172]
Hello,

I installed chromo using `pip`:
```
pip install --user chromo
```
Then in python I run the example from the [README](https://github.com/impy-project/chromo/blob/main/README.md), but I have the following error:
```
AttributeError: module 'chromo' has no attribute 'kinematics'
```

Additional info from `pip show chromo`
```
Name: chromo
Version: 0.0.1
Summary: Chromo
```

**Comment by afedynitch** [comment]
Hi Michael,

please add the `--pre` flag to `pip`. We're about to push the official release but need to finalize reviews of a few PRs. To install the current distribution run `pip install --pre --user chromo`. Let us know if this solves your problem.

**Comment by michael-pitt** [comment]
Thanks. I successfully installed chromo but encountered issues running the example, as my Python was 3.6. switching to 3.9 resolved the issues, and the code executed smoothly
