### ISSUE TITLE
Why chromo have no define？

### ISSUE THREAD

**Issue by Xiaozizhuo** [impy-project/chromo#181]
Hello dear developers, I'm a beginner at Chromo. When I use your package, I find that the contents of the chromo file do not have function definitions, so some functions cannot be used. How can this be solved?
![N`JXZ~AV_$20ERTI$TYY~JO](https://github.com/impy-project/chromo/assets/98071787/e197de3c-b2c0-4a64-a3f6-d440c460760d)

**Comment by afedynitch** [comment]
Hi @Xiaozizhuo ,

We’re waiting for one issue to be solved in numpy #127 before publishing the first full official release. We currently have a prerelease version of chromo with most features on pypi. To install it you need to add the ‘—pre’ option to ‘pip install’.

**Comment by Xiaozizhuo** [comment]
Thank you for your kind reply, here I have two questions: 1. How long will the latest version be online? 2. You said this installation method, I'm sorry I didn't understand what you mean.Do you mean to use 'pip install chromo' to install? I used this method, but the installed chromo definition file does not have any information in it.Can you please go into more detail?

**Comment by Xiaozizhuo** [comment]
Thank you for your help, following your method I managed to have a complete chroomo file definition. 

But there is also a new bug:numpy. core.multiarray failed to import.

I initially thought it was due to incompatibility between my version of numpy and the version of numpy used by your package, so I reinstalled a lot of versions, but to no avail.

Can you tell me what version of numpy is in your package? I would also like to hear your opinion, what is the problem causing this?

**Comment by jncots** [comment]
> I initially thought it was due to incompatibility

It is because of incompatibility. Chromo from pip works for numpy >=1.23. This should work:

```
pip install numpy==1.24.0
```

**Comment by Xiaozizhuo** [comment]
Thank you for your help, I have successfully run the example on the official page. I'm starting to learn the meaning of each function in your package now, and I'll ask for more advice in the future.
