### ISSUE TITLE
Errors in examples/compare_models.ipynb

### ISSUE THREAD

**Issue by jncots** [impy-project/chromo#66]
There is a problem with `examples/compare_models.ipynb`. It produces `RuntimeWarning: invalid value encountered in true_divide
  return np.log((self.p_tot + self.pz) / self.pt)` for some models.

**Comment by HDembinski** [comment]
That means that self.pt was zero, which is strange, it is very unlikely that pt is zero ever. This should be investigated.

**Comment by afedynitch** [comment]
@HDembinski we should not compute physics variables on unfiltered without filtering for final state. Some interaction models put special comment blocks on the event stack that don't have correct physics variables. For example, initial state particles don't have a pt.

**Comment by HDembinski** [comment]
Ok, good point. So this seems to be all in order? I think the warning is correct then and should be shown to the user.

If you think it should be silenced, the best way is to do this locally with `np.errstate` or by changing the calculation so that it never divides by zero (more involved).

**Comment by jncots** [comment]
It is probably occurs because of non-final particles.
