### ISSUE TITLE
Support CRMC style config file

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#93]
We want impy to be a drop-in replacement of CRMC, and thus we need to support CRMCs configuration file. The main use of this file is to allow the user to configure which particles should be decayed and which should be kept as final state.

The CRMC config file does not follow a standard configuration file syntax, so we should also support something modern like toml, yaml, or json (to be decided), in addition to the old format. The code needs to be structured so that the configuration can be read in at least the old and new format.

Also see related issue #94

**Comment by jncots** [comment]
Isn't this done in #133?

**Comment by HDembinski** [comment]
Not completely. The idea here was to have a parser for ther CRMC config file format. In #133 we provide our own "format",  it is just the Python API, which is a very efficient solution as it requires no extra code for the handling of config files.

**Comment by jncots** [comment]
> Not completely.
Ok. Then leave it open.

**Comment by HDembinski** [comment]
We could also declare this as a non-goal. I don't know how many users we would actually make happy by providing a parser for the CRMC format. It is not an easy feature to add and we have limited manpower.

@afedynitch What do you think? Should be close this?

**Comment by afedynitch** [comment]
Agree. Also not sure how many people were actually using it. If someone wants it badly we can reopen.
