### ISSUE TITLE
Decay post-processing of generator output

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#94]
Some generators do not decay all particles that are usually considered prompt and the decays are not configurable. For example, QGSJet returns undecayed pi0s and it is not possible to change this. We need a workaround for QGSJet. Perhaps there are other models which do not allow one to change which particles 

The workaround was already explored by Anatoli with the Pythia8DecayAfterburner. Pythia8 is ideal for this, because
- We have it now included in the distribution, so it is readily available.
- Several independent Pythia8 instances can be created in parallel, so QGSJet can hold its local instance to create the decays without interferring with the rest of the program.

Note: Running several Pythia8 instances in parallel is currently **not** supported, because all write to a global buffer that is allocated only once, but this should be comparably easy to change. There is no fundamental blocker which prevents this, as in case of the Fortran models.

The long-startup time of Pythia8 can probably be avoided if we use it only for decays.

Decaying particles with Pythia8 will require copying data from the QGSJet stack onto the Pythia8 stack and back. This can't be avoided.

See also #87

**Comment by jncots** [comment]
Solved in #167
