### ISSUE TITLE
Improve cross section readout for models other than Pythia8

### ISSUE THREAD

**Issue by afedynitch** [impy-project/chromo#96]
A new implementation by @HDembinski of the cross section function that can query different types of interaction cross sections, such as total, inelastic, diffractive, etc.

Actually, most models including DPMJET, SIBYLL, EPOS (not only Pythia) calculate these values using their internal models. To fix this one needs to point impy to the correct arrays/internal functions.

**Comment by HDembinski** [comment]
@afedynitch I added an example that generates plots of the cross-sections as function of E_cm for all models. Many models give strange output.

https://github.com/impy-project/impy/blob/c7a70a7defac464088a4c80ebfbb07d551a7d437/examples/cross_section.ipynb

**Comment by jncots** [comment]
Done in #169
